base_stations:
  - id: 41341 # mobile battery
    latitude: 30.629432 # powerline pole
    longitude: -96.476041
    A: -0.46 #-36.0 # RSSI at 1 meter
    N: 2.85
  - id: 41602
    latitude: 30.621299 # MCC tower
    longitude: -96.484742
    A: 0.47 #-36.0
    N: 3.05
  - id: 41628
    latitude: 30.633482 # OTA tower
    longitude: -96.487490
    A: 7.37 #-36.0
    N: 3.14

origin:
    latitude: 30.6319022476
    longitude: -96.4820809338

rates: # Hz
  measurement: 1 # rate of radio measurement
  yaw_raw: 80
  yaw_processed: 10
  velocity_raw: 100
  steer_raw: 100
  control_processed: 10

vehicle:
  steering_ratio: 15.15 # 15.15:1 steering wheel rotation to road wheel rotation
  wheelbase: 2.91592 # meters
