base_stations:
  - id: 41341 # mobile battery
    latitude: 30.637847 # motorcycle trailer
    longitude: -96.487087
    A: -5.42 #-36.0 # RSSI at 1 meter
    N: 1.93
  - id: 41628
    latitude: 30.640111 # north corner
    longitude: -96.484466
    A: 28.8 #-36.0
    N: 3.8
  - id: 41602
    latitude: 30.635757 # south corner
    longitude: -96.484472
    A: 31.68 #-36.0
    N: 3.66

origin:
    latitude: 30.6319022476
    longitude: -96.4820809338

rates: # Hz
  measurement: 10 # 1 rate of radio measurement
  yaw_raw: 80
  yaw_processed: 20 # 10
  velocity_raw: 100
  steer_raw: 100
  control_processed: 20 # 10

filter:
  rssi_variance: 400 # 4 dB^2
  rssi_variance_function_of_range: False
  rssi_range_threshold: 500 # meters; ignore RSSI beyond this range
  tof_variance: 2 # 25 (100 ns)^2
  tof_variance_function_of_range: True
  tof_range_threshold: 300 # meters; ignore ToF within this range
  imu_variance: 0.1 # radians^2
  velocity_variance: 0.2 # (m/2)^2
  steering_variance: 0.1 # radians^2

vehicle:
  steering_ratio: 15.15 # 15.15:1 steering wheel rotation to road wheel rotation
  wheelbase: 2.91592 # meters
