base_stations:
  - id: 41341 # mobile battery
    latitude: 30.637847 # motorcycle trailer
    longitude: -96.487087
    tx_power: 36
  - id: 41628
    latitude: 30.640111 # north corner
    longitude: -96.484466
    tx_power: 36
  - id: 41602
    latitude: 30.635757 # south corner
    longitude: -96.484472
    tx_power: 36

origin:
    latitude: 30.6319022476
    longitude: -96.4820809338

rates: # Hz
  measurement: 1 # rate of radio measurement
  yaw_raw: 80
  yaw_processed: 10
  velocity_raw: 100
  steer_raw: 100
  control_processed: 10

vehicle:
  steering_ratio: 15.15 # 15.15:1 steering wheel rotation to road wheel rotation
